---
# Please adjust to your needs (see https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
# and commit this file to your remote git repository to share the goodness with others.
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

vscode:
  extensions:
    - MS-CEINTL.vscode-language-pack-ja
    - equinusocio.vsc-material-theme-icons
    - redhat.java
    - Pivotal.vscode-boot-dev-pack
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven

# tasks:
#   - init: ./gradlew build
